#!/bin/sh
#  VNCScript.pbs
#  
#
#  Created by Ian Munro on 02/07/2016.
#
## ask PBS for time (format hh:mm:ss)
#PBS -l walltime=04:00:0
## ask for one node with 16 cpus and total 2gb memory (per node)
#PBS -l select=1:ncpus=20:mem=8gb
#PBS -J 1-5
#PBS -M i.munro@ic.ac.uk
#PBS -m e

#rm /work/imunro/result*

##load application module
module load fiji vnc

`vnc_start`

echo $PBS_ARRAY_INDEX

##command line
## DEBUG=1

/home/imunro/NodeScript.sh $PBS_ARRAY_INDEX

vnc_stop

exit


