#!/bin/sh
#  VNCScript.pbs
#  
#
#  Created by Ian Munro on 02/07/2016.
#
## ask PBS for time (format hh:mm:ss)
#PBS -l walltime=04:00:0
## ask for one node with 20 cpus and total 8gb memory (per node)
#PBS -l select=1:ncpus=24:mem=8gb
#PBS -J 1-4
#PBS -M i.munro@ic.ac.uk
#PBS -m e

##load application module
module load fiji vnc

echo "ncpus = "
echo $NCPUS

`vnc_start`


##command line
## DEBUG=1

/home/imunro/NodeScript.sh $PBS_ARRAY_INDEX

vnc_stop

exit


