#!/bin/sh

#  SerialScript.sh
#  
#
#  Created by Ian Munro on 09/06/2016.
#


## ask PBS for time (format hh:mm:ss)
#PBS -l walltime=00:09:01

## ask for one node with 16 cpus and total 2gb memory (per node)
#PBS -l select=1:ncpus=16:mem=2gb:ngpus=1

#PBS -q gpgpu
## This tells the batch manager to enqueue the job in the general gpgpu queue.


##load application module
module load fiji


##command line
DEBUG=1 /apps/fiji/Fiji.app/ImageJ-linux64 --ij2 -macro $HOME/TSTORM_macro.ijm $WORK

