#!/bin/sh

#  VNCScript.pbs
#  
#
#  Created by Ian Munro on 02/07/2016.
#


## ask PBS for time (format hh:mm:ss)
#PBS -l walltime=01:00:00

## ask for one node with 16 cpus and total 2gb memory (per node)
#PBS -l select=1:ncpus=16:mem=4gb


##load application module
module load fiji vnc

`vnc_start`

##command line
## DEBUG=1
ARGS=

/apps/fiji/Fiji.app/ImageJ-linux64 --ij2 -macro $HOME/TSTORM_macro.ijm $WORK 

vnc_stop


