#!/bin/sh
#  loc_ARRScript.pbs
#  
#
#  Created by Ian Munro on 02/07/2016.
#
## ask PBS for time (format hh:mm:ss)
#PBS -l walltime=08:00:0
## ask for ten jobs with 24 cpus and total 64gb memory (per node)
#PBS -l select=1:ncpus=48:ompthreads=48:mem=110gb
#PBS -J 1-4

##load application module
module load fiji vnc

`vnc_start`

##command line
## DEBUG=1

$HOME/Localisation/loc_NodeScript.sh

vnc_stop

exit


